#' Small synthetic bulk RNA-seq dataset for examples and tests
#'
#' A synthetic 20-gene x 8-sample `SummarizedExperiment`, 2 conditions (`control`,
#' `treated`) x 4 replicates, with 5 genes given a real mean-expression shift between
#' conditions. Used throughout this package's `@examples` blocks and testthat tests
#' instead of the real ~500MB+ alignment inputs (see
#' `data-raw/example_bulk_se.R` for exactly how it's generated — fixed random seed,
#' fully reproducible).
#'
#' @format A [SummarizedExperiment::SummarizedExperiment] with:
#' \describe{
#'   \item{assays$counts}{20 x 8 integer matrix of synthetic Poisson-distributed
#'     counts.}
#'   \item{colData$condition}{Factor, `control` or `treated`, 4 samples each.}
#'   \item{rowData$gene_symbol}{Real human breast-cancer-relevant gene symbols
#'     (TP53, BRCA1, ERBB2, ESR1, ...) attached to the synthetic counts purely so
#'     enrichment examples have recognisable gene names — the expression values
#'     themselves are entirely synthetic, not real measurements of these genes.}
#' }
#' @source Generated by `data-raw/example_bulk_se.R`.
"example_bulk_se"
